# Generated by Django 3.1.1 on 2020-09-08 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20200908_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
